-- V1: Initial schema — generated from pg_dump, cleaned up with readable constraint names
-- and complete enum check constraints matching current OperationType values.

-- ============================================================
-- TABLES (ordered by FK dependencies: independent first)
-- ============================================================

CREATE TABLE app_users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    role        varchar(255),
    CONSTRAINT app_users_username_uk UNIQUE (username),
    CONSTRAINT app_users_role_check CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE projects (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     varchar(255) NOT NULL,
    description              text,
    repo_url                 varchar(255),
    tech_context             text,
    local_path               varchar(255),
    structured_context       jsonb,
    integration_config       jsonb,
    claude_md_content        text,
    context_version          integer,
    last_scanned_at          timestamp(6),
    last_scanned_commit_hash varchar(255),
    deleted_at               timestamp(6),
    created_at               timestamp(6),
    updated_at               timestamp(6)
);

CREATE TABLE credentials (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key        varchar(255) NOT NULL,
    value      text NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT credentials_key_uk UNIQUE (key)
);

CREATE TABLE prompts (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(255) NOT NULL,
    content    text NOT NULL,
    version    integer,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT prompts_name_uk UNIQUE (name)
);

-- ============================================================
-- TABLES (with FK references)
-- ============================================================

CREATE TABLE project_memberships (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint NOT NULL,
    project_id bigint NOT NULL,
    role       varchar(255),
    created_at timestamp(6),
    CONSTRAINT project_memberships_user_project_uk UNIQUE (user_id, project_id),
    CONSTRAINT project_memberships_role_check CHECK (role IN ('OWNER', 'EDITOR', 'VIEWER')),
    CONSTRAINT fk_membership_user    FOREIGN KEY (user_id)    REFERENCES app_users(id),
    CONSTRAINT fk_membership_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE requirements (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_text        text NOT NULL,
    status          varchar(255),
    type            varchar(255),
    version         integer,
    sequence_number integer,
    project_id      bigint NOT NULL,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    CONSTRAINT requirements_status_check CHECK (status IN ('DRAFT', 'ANALYZING', 'ANALYZED', 'CLARIFYING', 'READY', 'APPROVED')),
    CONSTRAINT requirements_type_check   CHECK (type IN ('FEATURE', 'BUG')),
    CONSTRAINT fk_requirement_project    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE analyses (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structured_summary  text,
    assumptions         text,
    risk_level          varchar(255),
    risk_reason         text,
    affected_modules    text,
    po_summary          text,
    requirement_version integer,
    model_tier          varchar(255),
    context_version     integer,
    duration_ms         bigint,
    requirement_id      bigint NOT NULL,
    created_at          timestamp(6),
    CONSTRAINT analyses_model_tier_check CHECK (model_tier IN ('LIGHT', 'STANDARD', 'PREMIUM')),
    CONSTRAINT fk_analysis_requirement   FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

CREATE TABLE questions (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text    text NOT NULL,
    question_type    varchar(255),
    options          text,
    suggested_answer text,
    answer           text,
    status           varchar(255),
    answered_at      timestamp(6),
    analysis_id      bigint NOT NULL,
    created_at       timestamp(6),
    CONSTRAINT questions_status_check CHECK (status IN ('OPEN', 'ANSWERED', 'DISMISSED')),
    CONSTRAINT fk_question_analysis   FOREIGN KEY (analysis_id) REFERENCES analyses(id)
);

CREATE TABLE tasks (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                varchar(255) NOT NULL,
    description          text,
    acceptance_criteria  text,
    category             varchar(255),
    priority             varchar(255),
    sp_suggestion        integer,
    sp_rationale         text,
    sp_final             integer,
    sp_divergence_reason varchar(255),
    jira_key             varchar(255),
    analysis_id          bigint NOT NULL,
    dependency_task_id   bigint,
    created_at           timestamp(6),
    CONSTRAINT tasks_priority_check    CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT fk_task_analysis        FOREIGN KEY (analysis_id)       REFERENCES analyses(id),
    CONSTRAINT fk_task_dependency      FOREIGN KEY (dependency_task_id) REFERENCES tasks(id)
);

CREATE TABLE documents (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename       varchar(255) NOT NULL,
    content        text NOT NULL,
    summary        text,
    doc_type       varchar(255),
    project_id     bigint NOT NULL,
    requirement_id bigint,
    created_at     timestamp(6),
    CONSTRAINT documents_doc_type_check CHECK (doc_type IN ('MEETING_NOTES', 'ARCHITECTURE', 'EMAIL', 'SPECIFICATION', 'OTHER')),
    CONSTRAINT fk_document_project     FOREIGN KEY (project_id)     REFERENCES projects(id),
    CONSTRAINT fk_document_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

CREATE TABLE usage_records (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type     varchar(255) NOT NULL,
    model              varchar(255),
    input_tokens       integer,
    output_tokens      integer,
    total_tokens       integer,
    estimated_cost_usd numeric(10,6),
    duration_ms        bigint,
    project_id         bigint,
    created_at         timestamp(6),
    CONSTRAINT usage_records_operation_type_check CHECK (operation_type IN (
        'REQUIREMENT_ANALYSIS', 'TASK_BREAKDOWN', 'TASK_REFINEMENT',
        'STAKEHOLDER_SUMMARY', 'SUMMARY_REFINEMENT',
        'PROJECT_CONTEXT', 'PROJECT_CONTEXT_STRUCTURED',
        'CHANGE_IMPACT', 'HEALTH_CHECK',
        'DOCUMENT_SUMMARY', 'SP_SUGGESTION', 'FEATURE_SUGGESTION'
    ))
);
