-- V3: Organization entity — multi-tenancy Level 1 (shared schema, org FK)

CREATE TABLE organizations (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(255) NOT NULL,
    slug       varchar(255) NOT NULL,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT organizations_name_uk UNIQUE (name),
    CONSTRAINT organizations_slug_uk UNIQUE (slug)
);

-- Seed default organization
INSERT INTO organizations (id, name, slug, created_at, updated_at)
VALUES (1, 'Default', 'default', NOW(), NOW());

-- Add organization FK to app_users (nullable first, backfill, then NOT NULL)
ALTER TABLE app_users ADD COLUMN organization_id bigint;
UPDATE app_users SET organization_id = 1;
ALTER TABLE app_users ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE app_users ADD CONSTRAINT fk_user_organization
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- Add organization FK to projects (nullable first, backfill, then NOT NULL)
ALTER TABLE projects ADD COLUMN organization_id bigint;
UPDATE projects SET organization_id = 1;
ALTER TABLE projects ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE projects ADD CONSTRAINT fk_project_organization
    FOREIGN KEY (organization_id) REFERENCES organizations(id);

-- Ensure sequence is past the seeded ID
SELECT setval('organizations_id_seq', (SELECT COALESCE(MAX(id), 1) FROM organizations));
