-- V4: pgvector extension + requirement_embeddings table for organizational memory

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE requirement_embeddings (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id bigint NOT NULL,
    embedding      vector(1536) NOT NULL,
    is_rich        boolean NOT NULL DEFAULT false,
    embedded_at    timestamp(6),
    CONSTRAINT requirement_embeddings_req_uk UNIQUE (requirement_id),
    CONSTRAINT fk_embedding_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

-- IVFFlat index for approximate nearest-neighbor cosine similarity search
-- lists=100 is appropriate for up to ~1M vectors; adjust as data grows
CREATE INDEX requirement_embeddings_ivfflat_idx
    ON requirement_embeddings USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);
