CREATE TABLE project_services (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id                bigint NOT NULL,
    name                      varchar(255) NOT NULL,
    service_type              varchar(50) NOT NULL,
    repo_url                  varchar(500),
    local_path                varchar(500),
    default_branch            varchar(255),
    owner_team                varchar(255),
    active                    boolean NOT NULL DEFAULT true,
    tech_context              text,
    structured_context        jsonb,
    context_version           integer NOT NULL DEFAULT 0,
    last_scanned_at           timestamp(6),
    last_scanned_commit_hash  varchar(255),
    created_at                timestamp(6),
    updated_at                timestamp(6),
    CONSTRAINT fk_project_services_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT project_services_name_uk UNIQUE (project_id, name)
);

CREATE TABLE service_dependencies (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       bigint NOT NULL,
    from_service_id  bigint NOT NULL,
    to_service_id    bigint NOT NULL,
    dependency_type  varchar(50) NOT NULL DEFAULT 'SYNC',
    created_at       timestamp(6),
    CONSTRAINT fk_service_dep_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_service_dep_from FOREIGN KEY (from_service_id) REFERENCES project_services(id) ON DELETE CASCADE,
    CONSTRAINT fk_service_dep_to FOREIGN KEY (to_service_id) REFERENCES project_services(id) ON DELETE CASCADE,
    CONSTRAINT service_dependencies_unique UNIQUE (project_id, from_service_id, to_service_id),
    CONSTRAINT service_dependencies_not_self CHECK (from_service_id <> to_service_id)
);

ALTER TABLE tasks
    ADD COLUMN service_id bigint;

ALTER TABLE tasks
    ADD CONSTRAINT fk_task_service FOREIGN KEY (service_id) REFERENCES project_services(id);

CREATE INDEX idx_project_services_project_id ON project_services(project_id);
CREATE INDEX idx_service_dependencies_project_id ON service_dependencies(project_id);
CREATE INDEX idx_tasks_service_id ON tasks(service_id);
