CREATE TABLE task_sync_refs (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id           bigint NOT NULL,
    provider          varchar(20) NOT NULL,
    external_ref      varchar(255) NOT NULL,
    target            varchar(500),
    sync_state        varchar(30) NOT NULL DEFAULT 'SYNCED',
    last_verified_at  timestamp(6),
    created_at        timestamp(6),
    updated_at        timestamp(6),
    CONSTRAINT fk_task_sync_ref_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT task_sync_ref_unique UNIQUE (task_id, provider, target, external_ref)
);

CREATE INDEX idx_task_sync_refs_task_id ON task_sync_refs(task_id);
CREATE INDEX idx_task_sync_refs_provider ON task_sync_refs(provider);
