package com.scopesmith.entity;

public enum OperationType {
    REQUIREMENT_ANALYSIS,
    TASK_BREAKDOWN,
    TASK_REFINEMENT,
    STAKEHOLDER_SUMMARY,
    SUMMARY_REFINEMENT,
    PROJECT_CONTEXT,
    PROJECT_CONTEXT_STRUCTURED,
    CHANGE_IMPACT,
    HEALTH_CHECK
}
